# Generated by Django 5.2 on 2025-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('support', models.BooleanField()),
            ],
        ),
    ]
